### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Kureev** [Kureev/react-native-blur#1]
- [x] Working prototype
- [x] More examples (your ideas are very welcome)
- [x] Support different types of blur: `light`, `extra light` and `dark`

**Comment by MelanieCLopez** [comment]
The Apache Indians

**Comment by MelanieCLopez** [comment]
The Apache Indians were associated with the label "Shaman" basically this is what pop out after the has been an overwhelming injustices of acta against them typically woman mothers because they have no one to defend them and the wait on God enduring heartache. That once time has matured it's like a cycle begins to come back in the direction it began its an eye opening awakening experience. This rare gems used to be called witch doctor but basically they began to understand other peoples intentions around them.
